<?php

return [
    [
        'name' => 'The Legend of Zelda: Breath of the Wild',
        'price' => 59.99,
        'year_of_publication' => 2017,
        'pegi' => 12,
        'cover' => 'img/videogames/covers/the_legend_of_zelda_breath_of_the_wild.jpg',
        'genre_ids' => [1, 2],
        'console_ids' => [3],
        'developer' => 'Nintendo EPD',
        'publisher' => 'Nintendo',
        'description' => 'Un’avventura open-world che reinventa la serie, offrendo un mondo vasto e interattivo da esplorare liberamente.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Elden Ring',
        'price' => 59.99,
        'year_of_publication' => 2022,
        'pegi' => 16,
        'cover' => 'img/videogames/covers/elden_ring.jpg',
        'genre_ids' => [3, 4],
        'console_ids' => [1, 2, 4],
        'developer' => 'FromSoftware',
        'publisher' => 'Bandai Namco Entertainment',
        'description' => 'Un action RPG che unisce la profondità narrativa di George R.R. Martin con il gameplay impegnativo tipico di FromSoftware.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Minecraft',
        'price' => 26.95,
        'year_of_publication' => 2011,
        'pegi' => 7,
        'cover' => 'img/videogames/covers/minecraft.jpg',
        'genre_ids' => [8, 9],
        'console_ids' => [3, 5, 6],
        'developer' => 'Mojang Studios',
        'publisher' => 'Mojang Studios',
        'description' => 'Un gioco sandbox che permette ai giocatori di costruire e esplorare mondi generati proceduralmente.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'FIFA 24',
        'price' => 69.99,
        'year_of_publication' => 2023,
        'pegi' => 3,
        'cover' => 'img/videogames/covers/fifa_24.jpg',
        'genre_ids' => [6],
        'console_ids' => [1, 2, 5],
        'developer' => 'EA Sports',
        'publisher' => 'Electronic Arts',
        'description' => 'L\'ultima edizione della serie calcistica più realistica, con nuove modalità e squadre aggiornate.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Call of Duty: Modern Warfare III',
        'price' => 69.99,
        'year_of_publication' => 2023,
        'pegi' => 18,
        'cover' => 'img/videogames/covers/call_of_duty_modern_warfare_iii.jpg',
        'genre_ids' => [7],
        'console_ids' => [1, 2],
        'developer' => 'Sledgehammer Games, Infinity Ward, Treyarch',
        'publisher' => 'Activision',
        'description' => 'Un FPS adrenalinico che continua la saga con una campagna intensa, multiplayer rinnovato e la modalità Zombies.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Super Mario Odyssey',
        'price' => 59.99,
        'year_of_publication' => 2017,
        'pegi' => 7,
        'cover' => 'img/videogames/covers/super_mario_odyssey.jpg',
        'genre_ids' => [1, 2],
        'console_ids' => [3],
        'developer' => 'Nintendo EPD',
        'publisher' => 'Nintendo',
        'description' => 'Un platform 3D colorato e creativo che accompagna Mario in un viaggio intorno al mondo per salvare Peach da Bowser.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Hogwarts Legacy',
        'price' => 69.99,
        'year_of_publication' => 2023,
        'pegi' => 16,
        'cover' => 'img/videogames/covers/hogwarts_legacy.jpg',
        'genre_ids' => [3, 4],
        'console_ids' => [1, 2, 4],
        'developer' => 'Portkey Games',
        'publisher' => 'Warner Bros. Games',
        'description' => 'Un gioco action RPG ambientato nell’universo di Harry Potter, che permette ai giocatori di vivere la propria avventura magica a Hogwarts.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Animal Crossing: New Horizons',
        'price' => 59.99,
        'year_of_publication' => 2020,
        'pegi' => 3,
        'cover' => 'img/videogames/covers/animal_crossing_new_horizons.jpg',
        'genre_ids' => [8, 9],
        'console_ids' => [3],
        'developer' => 'Nintendo EPD',
        'publisher' => 'Nintendo',
        'description' => 'Un gioco sandbox rilassante dove i giocatori possono costruire e personalizzare la propria isola tropicale.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Gran Turismo 7',
        'price' => 69.99,
        'year_of_publication' => 2022,
        'pegi' => 3,
        'cover' => 'img/videogames/covers/gran_turismo_7.jpg',
        'genre_ids' => [6],
        'console_ids' => [1, 2],
        'developer' => 'Polyphony Digital',
        'publisher' => 'Sony Interactive Entertainment',
        'description' => 'Un simulatore di guida realistico che offre una vasta selezione di auto e tracciati, pensato per gli appassionati di motori.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Resident Evil 4 Remake',
        'price' => 69.99,
        'year_of_publication' => 2023,
        'pegi' => 18,
        'cover' => 'img/videogames/covers/resident_evil_4_remake.jpg',
        'genre_ids' => [4],
        'console_ids' => [1, 2, 4],
        'developer' => 'Capcom',
        'publisher' => 'Capcom',
        'description' => 'Un remake moderno del celebre survival horror, con grafica aggiornata, gameplay rinnovato e atmosfera intensa.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
    'name' => 'Persona 5: The Phantom X',
    'price' => 49.99,
    'year_of_publication' => 2025,
    'pegi' => 16,
    'cover' => 'img/videogames/covers/persona_5_the_phantom_x.jpg',
    'genre_ids' => [3, 4],
    'console_ids' => [3, 5],
    'developer' => 'Perfect World Games',
    'publisher' => 'Sega, Atlus',
    'description' => 'Un nuovo capitolo della serie Persona, ambientato in un universo parallelo con elementi gacha e nuove meccaniche di gioco.',
    'placeholder' => 'img/videogames/placeholder.jpg'
],
[
    'name' => 'Clair Obscur: Expedition 33',
    'price' => 59.99,
    'year_of_publication' => 2025,
    'pegi' => 18,
    'cover' => 'img/videogames/covers/clair_obscur_expedition_33.jpg',
    'genre_ids' => [4],
    'console_ids' => [1, 2],
    'developer' => 'Sandfall Interactive',
    'publisher' => 'Baroque',
    'description' => 'Un RPG con estetica barocca e ambientazione Belle Époque, che racconta una storia emozionante e unica.',
    'placeholder' => 'img/videogames/placeholder.jpg'
],
[
    'name' => 'Doom: The Dark Ages',
    'price' => 69.99,
    'year_of_publication' => 2025,
    'pegi' => 18,
    'cover' => 'img/videogames/covers/doom_the_dark_ages.jpg',
    'genre_ids' => [7],
    'console_ids' => [1, 2],
    'developer' => 'id Software',
    'publisher' => 'Bethesda Softworks',
    'description' => 'Un ritorno alle origini della serie Doom, con ambientazioni medievali e combattimenti frenetici.',
    'placeholder' => 'img/videogames/placeholder.jpg'
],
[
    'name' => 'Borderlands 4',
    'price' => 69.99,
    'year_of_publication' => 2025,
    'pegi' => 18,
    'cover' => 'img/videogames/covers/borderlands_4.jpg',
    'genre_ids' => [7],
    'console_ids' => [1, 2],
    'developer' => 'Gearbox Software',
    'publisher' => '2K Games',
    'description' => 'Un nuovo capitolo della serie Borderlands, con nuove ambientazioni, personaggi e meccaniche di gioco.',
    'placeholder' => 'img/videogames/placeholder.jpg'
],
[
    'name' => 'Split Fiction',
    'price' => 59.99,
    'year_of_publication' => 2025,
    'pegi' => 12,
    'cover' => 'img/videogames/covers/split_fiction.jpg',
    'genre_ids' => [1, 2],
    'console_ids' => [1, 2],
    'developer' => 'Hazelight Studios',
    'publisher' => 'EA Originals',
    'description' => 'Un gioco cooperativo che mescola mondi di fantasia e fantascienza, con meccaniche di gioco innovative.',
    'placeholder' => 'img/videogames/placeholder.jpg'
],
[
    'name' => 'Assassin’s Creed Shadows',
    'price' => 69.99,
    'year_of_publication' => 2025,
    'pegi' => 18,
    'cover' => 'img/videogames/covers/assassins_creed_shadows.jpg',
    'genre_ids' => [4],
    'console_ids' => [1, 2],
    'developer' => 'Ubisoft Quebec',
    'publisher' => 'Ubisoft',
    'description' => 'Un nuovo capitolo della serie Assassin’s Creed, ambientato nel Giappone feudale con protagonisti un samurai e una kunoichi.',
    'placeholder' => 'img/videogames/placeholder.jpg'
],
[
    'name' => 'Avowed',
    'price' => 59.99,
    'year_of_publication' => 2025,
    'pegi' => 16,
    'cover' => 'img/videogames/covers/avowed.jpg',
    'genre_ids' => [3, 4],
    'console_ids' => [1],
    'developer' => 'Obsidian Entertainment',
    'publisher' => 'Xbox Game Studios',
    'description' => 'Un RPG fantasy ambientato nel mondo di Eora, con combattimenti tattici e una trama profonda.',
    'placeholder' => 'img/videogames/placeholder.jpg'
],
[
    'name' => 'Pokémon Legends: Z-A',
    'price' => 59.99,
    'year_of_publication' => 2025,
    'pegi' => 7,
    'cover' => 'img/videogames/covers/pokemon_legends_z_a.jpg',
    'genre_ids' => [3],
    'console_ids' => [3],
    'developer' => 'Game Freak',
    'publisher' => 'Nintendo',
    'description' => 'Un nuovo capitolo della serie Pokémon, ambientato in una Lumiose City ispirata a Parigi.',
    'placeholder' => 'img/videogames/placeholder.jpg'
],
[
    'name' => 'Monster Hunter Wilds',
    'price' => 69.99,
    'year_of_publication' => 2025,
    'pegi' => 16,
    'cover' => 'img/videogames/covers/monster_hunter_wilds.jpg',
    'genre_ids' => [8],
    'console_ids' => [1, 2],
    'developer' => 'Capcom',
    'publisher' => 'Capcom',
    'description' => 'Un nuovo capitolo della serie Monster Hunter, con ambientazioni open-world e nuove creature da cacciare.',
    'placeholder' => 'img/videogames/placeholder.jpg'
],
[
    'name' => 'Ghost of Yotei',
    'price' => 69.99,
    'year_of_publication' => 2025,
    'pegi' => 18,
    'cover' => 'img/videogames/covers/ghost_of_yotei.jpg',
    'genre_ids' => [4],
    'console_ids' => [1],
    'developer' => 'Sucker Punch Productions',
    'publisher' => 'Sony Interactive Entertainment',
    'description' => 'Un nuovo capitolo spirituale di Ghost of Tsushima, ambientato sull’isola di Hokkaido, con nuove meccaniche stealth e narrativa profonda.',
    'placeholder' => 'img/videogames/placeholder.jpg'
],
];
