<?php

return [
    [
        'name' => 'The Legend of Zelda: Breath of the Wild',
        'price' => 59.99,
        'year_of_publication' => 2017,
        'pegi' => 12,
        'cover' => 'img/videogames/covers/the_legend_of_zelda_breath_of_the_wild.jpg',
        'genre_ids' => [1, 2],
        'console_ids' => [3],
        'developer' => 'Nintendo EPD',
        'publisher' => 'Nintendo',
        'description' => 'Un’avventura open-world che reinventa la serie, offrendo un mondo vasto e interattivo da esplorare liberamente.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Elden Ring',
        'price' => 59.99,
        'year_of_publication' => 2022,
        'pegi' => 16,
        'cover' => 'img/videogames/covers/elden_ring.jpg',
        'genre_ids' => [3, 4],
        'console_ids' => [1, 2, 4],
        'developer' => 'FromSoftware',
        'publisher' => 'Bandai Namco Entertainment',
        'description' => 'Un action RPG che unisce la profondità narrativa di George R.R. Martin con il gameplay impegnativo tipico di FromSoftware.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Minecraft',
        'price' => 26.95,
        'year_of_publication' => 2011,
        'pegi' => 7,
        'cover' => 'img/videogames/covers/minecraft.jpg',
        'genre_ids' => [8, 9],
        'console_ids' => [3, 5, 6],
        'developer' => 'Mojang Studios',
        'publisher' => 'Mojang Studios',
        'description' => 'Un gioco sandbox che permette ai giocatori di costruire e esplorare mondi generati proceduralmente.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'FIFA 24',
        'price' => 69.99,
        'year_of_publication' => 2023,
        'pegi' => 3,
        'cover' => 'img/videogames/covers/fifa_24.jpg',
        'genre_ids' => [6],
        'console_ids' => [1, 2, 5],
        'developer' => 'EA Sports',
        'publisher' => 'Electronic Arts',
        'description' => 'L\'ultima edizione della serie calcistica più realistica, con nuove modalità e squadre aggiornate.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Call of Duty: Modern Warfare III',
        'price' => 69.99,
        'year_of_publication' => 2023,
        'pegi' => 18,
        'cover' => 'img/videogames/covers/call_of_duty_modern_warfare_iii.jpg',
        'genre_ids' => [7],
        'console_ids' => [1, 2],
        'developer' => 'Sledgehammer Games, Infinity Ward, Treyarch',
        'publisher' => 'Activision',
        'description' => 'Un FPS adrenalinico che continua la saga con una campagna intensa, multiplayer rinnovato e la modalità Zombies.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Super Mario Odyssey',
        'price' => 59.99,
        'year_of_publication' => 2017,
        'pegi' => 7,
        'cover' => 'img/videogames/covers/super_mario_odyssey.jpg',
        'genre_ids' => [1, 2],
        'console_ids' => [3],
        'developer' => 'Nintendo EPD',
        'publisher' => 'Nintendo',
        'description' => 'Un platform 3D colorato e creativo che accompagna Mario in un viaggio intorno al mondo per salvare Peach da Bowser.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Hogwarts Legacy',
        'price' => 69.99,
        'year_of_publication' => 2023,
        'pegi' => 16,
        'cover' => 'img/videogames/covers/hogwarts_legacy.jpg',
        'genre_ids' => [3, 4],
        'console_ids' => [1, 2, 4],
        'developer' => 'Portkey Games',
        'publisher' => 'Warner Bros. Games',
        'description' => 'Un gioco action RPG ambientato nell’universo di Harry Potter, che permette ai giocatori di vivere la propria avventura magica a Hogwarts.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Animal Crossing: New Horizons',
        'price' => 59.99,
        'year_of_publication' => 2020,
        'pegi' => 3,
        'cover' => 'img/videogames/covers/animal_crossing_new_horizons.jpg',
        'genre_ids' => [8, 9],
        'console_ids' => [3],
        'developer' => 'Nintendo EPD',
        'publisher' => 'Nintendo',
        'description' => 'Un gioco sandbox rilassante dove i giocatori possono costruire e personalizzare la propria isola tropicale.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Gran Turismo 7',
        'price' => 69.99,
        'year_of_publication' => 2022,
        'pegi' => 3,
        'cover' => 'img/videogames/covers/gran_turismo_7.jpg',
        'genre_ids' => [6],
        'console_ids' => [1, 2],
        'developer' => 'Polyphony Digital',
        'publisher' => 'Sony Interactive Entertainment',
        'description' => 'Un simulatore di guida realistico che offre una vasta selezione di auto e tracciati, pensato per gli appassionati di motori.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
    [
        'name' => 'Resident Evil 4 Remake',
        'price' => 69.99,
        'year_of_publication' => 2023,
        'pegi' => 18,
        'cover' => 'img/videogames/covers/resident_evil_4_remake.jpg',
        'genre_ids' => [4],
        'console_ids' => [1, 2, 4],
        'developer' => 'Capcom',
        'publisher' => 'Capcom',
        'description' => 'Un remake moderno del celebre survival horror, con grafica aggiornata, gameplay rinnovato e atmosfera intensa.',
        'placeholder' => 'img/videogames/placeholder.jpg'
    ],
];
