<?php

return [
    [
        'name' => 'The Legend of Zelda: Breath of the Wild',
        'price' => 59.99,
        'year_of_publication' => 2017,
        'pegi' => 12,
        'cover' => 'img/videogames/the_legend_of_zelda_breath_of_the_wild.jpg',
        'genre_ids' => [1, 2],
        'console_ids' => [3],
        'developer' => 'Nintendo EPD',
        'publisher' => 'Nintendo',
        'description' => 'Un’avventura open-world che reinventa la serie, offrendo un mondo vasto e interattivo da esplorare liberamente.',
    ],
    [
        'name' => 'Elden Ring',
        'price' => 59.99,
        'year_of_publication' => 2022,
        'pegi' => 16,
        'cover' => 'img/videogames/elden_ring.jpg',
        'genre_ids' => [3, 4],
        'console_ids' => [1, 2, 4],
        'developer' => 'FromSoftware',
        'publisher' => 'Bandai Namco Entertainment',
        'description' => 'Un action RPG che unisce la profondità narrativa di George R.R. Martin con il gameplay impegnativo tipico di FromSoftware.',
    ],
    [
        'name' => 'Minecraft',
        'price' => 26.95,
        'year_of_publication' => 2011,
        'pegi' => 7,
        'cover' => 'img/videogames/minecraft.jpg',
        'genre_ids' => [8, 9],
        'console_ids' => [3, 5, 6],
        'developer' => 'Mojang Studios',
        'publisher' => 'Mojang Studios',
        'description' => 'Un gioco sandbox che permette ai giocatori di costruire e esplorare mondi generati proceduralmente.',
    ],
    [
        'name' => 'FIFA 24',
        'price' => 69.99,
        'year_of_publication' => 2023,
        'pegi' => 3,
        'cover' => 'img/videogames/fifa_24.jpg',
        'genre_ids' => [6],
        'console_ids' => [1, 2, 5],
        'developer' => 'EA Sports',
        'publisher' => 'Electronic Arts',
        'description' => 'L\'ultima edizione della serie calcistica più realistica, con nuove modalità e squadre aggiornate.',
    ],
    [
        'name' => 'Call of Duty: Modern Warfare III',
        'price' => 69.99,
        'year_of_publication' => 2023,
        'pegi' => 18,
        'cover' => 'img/videogames/call_of_duty_modern_warfare_iii.jpg',
        'genre_ids' => [7],
        'console_ids' => [1, 2],
        'developer' => 'Sledgehammer Games, Infinity Ward, Treyarch',
        'publisher' => 'Activision',
        'description' => 'Un FPS adrenalinico che continua la saga con una campagna intensa, multiplayer rinnovato e la modalità Zombies.',
    ],
];
